export const AUTH_PORTALS = {
  donor: {
    key: 'donor',
    label: 'Donor',
    accent: '#F25F4C',
    surface: '#FFF1EE',
    textAccent: '#C2410C',
    icon: 'gift-outline',
    welcomeCopy: 'Share surplus food, approve requests, and keep every meal moving.',
    loginEyebrow: 'Donor login',
    loginTitle: 'Turn today\'s surplus into someone\'s dinner.',
    loginCopy: 'Track active donations, respond quickly to requests, and keep handoffs smooth.',
    signupTitle: 'Create your donor account',
    signupCopy: 'Set up your donor profile and start posting surplus food in minutes.',
    signupAllowed: true,
  },
  ngo: {
    key: 'ngo',
    label: 'NGO',
    accent: '#0F766E',
    surface: '#ECFEF9',
    textAccent: '#115E59',
    icon: 'business-outline',
    welcomeCopy: 'Request food faster, follow pickup status, and coordinate distribution with clarity.',
    loginEyebrow: 'NGO login',
    loginTitle: 'Find nearby food support without the chaos.',
    loginCopy: 'Browse fresh donations, manage requests, and keep your team aligned on pickups.',
    signupTitle: 'Create your NGO account',
    signupCopy: 'Register your organization and begin requesting available meals for your community.',
    signupAllowed: true,
  },
  volunteer: {
    key: 'volunteer',
    label: 'Volunteer',
    accent: '#2563EB',
    surface: '#EFF6FF',
    textAccent: '#1D4ED8',
    icon: 'bicycle-outline',
    welcomeCopy: 'See nearby tasks, confirm pickups, and help food reach people on time.',
    loginEyebrow: 'Volunteer login',
    loginTitle: 'Jump into deliveries that matter today.',
    loginCopy: 'Access pickup assignments, track routes, and support reliable last-mile delivery.',
    signupTitle: 'Create your volunteer account',
    signupCopy: 'Share your area and vehicle details so the team can route nearby delivery work.',
    signupAllowed: true,
  },
  admin: {
    key: 'admin',
    label: 'Admin',
    accent: '#111827',
    surface: '#F3F4F6',
    textAccent: '#111827',
    icon: 'shield-checkmark-outline',
    welcomeCopy: 'Monitor platform activity, protect trust, and keep the NeedFeed network compliant.',
    loginEyebrow: 'Admin login',
    loginTitle: 'Open the control room for donors, NGOs, and volunteers.',
    loginCopy: 'Review operations, investigate issues, and manage the platform from one place.',
    signupTitle: 'Admin accounts are provisioned internally',
    signupCopy: 'Use your assigned credentials to continue into the admin control room.',
    signupAllowed: false,
  },
};

export const LOGIN_ROLE_ORDER = ['donor', 'ngo', 'volunteer', 'admin'];
export const SIGNUP_ROLE_ORDER = ['donor', 'ngo', 'volunteer'];

export const getPortalConfig = (role) => AUTH_PORTALS[role] || AUTH_PORTALS.donor;
